apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-watch-pods
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-pod-watcher
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-service-account
    namespace: {{ .Values.namespace }}
